version: '3'

services:
  timekpr-next-remote:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./conf.py:/app/conf.py"
    restart: unless-stopped
    ports:
      - "${TIMEKPR_PORT:-8080}:8080"
    environment:
      TZ: ${TIMEKPR_TZ:-America/Los_Angeles}